### ISSUE TITLE
Minus plus button redesign

### ISSUE THREAD

**Issue by raphelkabir** [SleepingApps/Slurp#64]
Minus and plus button on DailyItem are to be redesigned

**Comment by raphelkabir** [comment]
![image](https://user-images.githubusercontent.com/69769524/122438600-c9a2da00-cf92-11eb-99c9-6a5329050e58.png)

**Comment by LucaFalasca** [comment]
ciaso 
![immagine](https://user-images.githubusercontent.com/30274870/122438662-39b55e00-cf9b-11eb-9f95-46708be71402.png)

**Comment by raphelkabir** [comment]
Refer to #98 from now on
