### ISSUE TITLE
Some portion consumed do not update in the UI

### ISSUE THREAD

**Issue by LucaFalasca** [SleepingApps/Slurp#83]
In seguito al Ticket #82 si è rilevato un problema sull'observer che non aggiorna il automatico i cambiamenti del database.
Adesso quando si aggiorna una foodIstance che ha le porzioni in comune con altri, sul database vengono aggiornati tutti contemporaneamente. Ciò non accade sull'UI perchè essa non viene aggiornata dall'observer automaticamente ma manualmente (era perchè comportava bug grafici o lentezza nell'aggiornamento se non sbaglio).

**Comment by raphelkabir** [comment]
Sistemato ma non ho idea con quale commit e' stato sistemato sorry
